correction  pipeline

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -175,15 +175,14 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Debug Secrets (Check if empty)
+      - name: Check secrets availability
         run: |
-          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then echo "USERNAME is EMPTY!"; else echo "USERNAME is set."; fi
-          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then echo "TOKEN is EMPTY!"; else echo "TOKEN is set."; fi
+          test -n "${{ secrets.DOCKERHUB_USERNAME }}" || (echo "DOCKERHUB_USERNAME is missing" && exit 1)
+          test -n "${{ secrets.DOCKERHUB_TOKEN }}" || (echo "DOCKERHUB_TOKEN is missing" && exit 1)
 
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
-          # On ne spécifie PAS de paramètre 'registry:' pour Docker Hub !
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
